In [2]:
import numpy as np


In [2]:
arr=np.array([1500,3000,5000])

In [3]:
daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [6]:
print("Cost Price Shape:", arr.shape)
print("Cost Price Dimension:", arr.ndim)

print("Daily Sales Shape:", daily_sales.shape)
print("Daily Sales Dimension:", daily_sales.ndim)

Cost Price Shape: (3,)
Cost Price Dimension: 1
Daily Sales Shape: (3, 4)
Daily Sales Dimension: 2


In [7]:
daily_sales_bonus = daily_sales+2
print(daily_sales_bonus)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [8]:
revenue = daily_sales*arr[:, np.newaxis]
print(revenue)

[[15000 22500 12000 18000]
 [15000 21000 12000 18000]
 [10000 15000 10000 20000]]


In [9]:
tpdrevenue = revenue.sum(axis=0)
print(tpdrevenue)

[40000 58500 34000 56000]


In [10]:
sqrt_values = np.sqrt(daily_sales)
print(sqrt_values)

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


Q3

In [5]:
sales=np.array([[120,150,130,170],[200,220,210,230],[80,90,85,95]])

In [6]:
sales[1, :]


array([200, 220, 210, 230])

In [7]:
sales[:, 0:2]


array([[120, 150],
       [200, 220],
       [ 80,  90]])

In [8]:
sales[2][3]


np.int64(95)

In [9]:
sales[0:2, 0:2]


array([[120, 150],
       [200, 220]])

Q4

In [18]:
sales = np.array([
    [120,150,130,170],
    [200,220,210,230],
    [80, 90, 85, 95]
])

In [22]:
flat_sales = sales.reshape(12,)
# OR
flat_sales = sales.reshape(-1)
flat_sales


array([120, 150, 130, 170, 200, 220, 210, 230,  80,  90,  85,  95])

In [23]:
sales_2x6 = sales.reshape(2, 6)
print(sales_2x6)


[[120 150 130 170 200 220]
 [210 230  80  90  85  95]]


In [24]:
discounts = np.linspace(0, 100, 10)
discounts


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Q5

In [28]:
sales = np.array([
    [120,150,130,170],
    [200,220,210,230],
    [80, 90, 85, 95]
])

In [32]:
predicted_sales = np.random.randint(0, 21, size=(3,4))
print("Predicted Sales:\n", predicted_sales)

Predicted Sales:
 [[ 2  3 16 13]
 [15 19 18  7]
 [ 3  8  4  7]]


In [33]:
random_values = np.random.rand(5)
print("Random values between 0 and 1:\n", random_values)

Random values between 0 and 1:
 [0.39775114 0.41946238 0.68738516 0.41673842 0.58646464]


In [34]:
total_items = np.sum(sales)
print("Total items sold over all days:", total_items)

Total items sold over all days: 1780


In [35]:
product_wise_total = np.sum(sales, axis=1)
print("Total items sold for each product:", product_wise_total)

Total items sold for each product: [570 860 350]
