Exercise 2

In [2]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])


In [3]:
marks.shape


(5, 3)

In [4]:
marks.size


15

In [5]:
marks.dtype


dtype('int64')

In [6]:
marks[1]


array([45, 60, 55])

In [7]:
marks[:, 2]


array([90, 55, 95, 35, 75])

In [9]:
marks[0, 1]
int(marks[0, 1])

85

Part B

In [12]:
avg_students = marks.mean(axis=1)
avg_students

array([84.33333333, 53.33333333, 91.66666667, 35.        , 70.        ])

In [11]:
avg_subjects = marks.mean(axis=0)
avg_subjects

array([61.2, 69.4, 70. ])

In [13]:
top_students = avg_students >= 80
top_students

array([ True, False,  True, False, False])

In [14]:
marks[top_students]

array([[78, 85, 90],
       [88, 92, 95]])

In [16]:
marks = marks + 5
marks

array([[ 88,  95, 100],
       [ 55,  70,  65],
       [ 98, 102, 105],
       [ 40,  50,  45],
       [ 75,  80,  85]])

Part C

In [17]:
marks = np.array([78, 45, 60, 30, 90])


In [18]:
status = np.where(marks >= 50, 1, 0)
print(status)


[1 0 1 0 1]


In [19]:
cleaned_marks = np.where(marks < 40, 0, marks)
print(cleaned_marks)

[78 45 60  0 90]


Part D

In [20]:
avg = np.array([92, 76, 63, 48, 85])

In [21]:
score = np.where(avg >= 85, 10,
         np.where(avg >= 70, 8,
         np.where(avg >= 50, 6, 0)))

print(score)

[10  8  6  0 10]


In [22]:
grade = np.where(avg >= 85, 'A',
         np.where(avg >= 70, 'B',
         np.where(avg >= 50, 'C', 'No Grade')))

print(grade)

['A' 'B' 'C' 'No Grade' 'A']


Part E

In [23]:
marks = np.array([[78, 65, 90],
                  [45, 88, 72]])


In [24]:
backup = marks.copy()


In [25]:
marks[0, 0] = 0


In [26]:
print("Original marks:")
print(marks)

print("Backup marks:")
print(backup)


Original marks:
[[ 0 65 90]
 [45 88 72]]
Backup marks:
[[78 65 90]
 [45 88 72]]
